### ISSUE TITLE
axios could not be resolved

### ISSUE THREAD

**Issue by renansantos** [hanneskuettner/directus-extension-inline-form-interface#1]
Hi, there!
I just installed the extension over Directus 10.9.3 and got the message `"axios" is imported by "extensions/interfaces/inline-form-interface/index.js", but could not be resolved – treating it as an external dependency.`
Then, the extension is listed and "enabled", but the interface doesn't show up in the field settings.

**Comment by hanneskuettner** [comment]
This should not happen anymore in v1.2.0. If it still occurs I'll reopen this issue.
