### ISSUE TITLE
1:1 cascade delete

### ISSUE THREAD

**Issue by dbargaud** [hanneskuettner/directus-extension-inline-form-interface#3]
Hi,

this is great work and I like to use it.

Could you add an option to choose if the data must be delete when the "parent" is deleted ?
This is useful in the case of a 1:1 relation.
Right now, I did not find a way to handle it (except a trigger in the database which seems a bit "dirty" :) )

Thank you for your work.

David

**Comment by rasco** [comment]
@dbargaud as far as i can see, that is already not a feature in the built-in Directus M2O relation? 
so i guess this is more of a directus issue, and not concerning this interface.

**Comment by hanneskuettner** [comment]
As far as I can see (don't have a computer to replicate it right now) the recommended way is through a DB trigger or flow as M2O does not support cascade delete through the app itself. This is not the job of an interface.
